// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddNodeInput struct {
	IP       string        `json:"ip"`
	Port     *string       `json:"port,omitempty"`
	Username string        `json:"username"`
	Password string        `json:"password"`
	Labels   []*LabelInput `json:"labels"`
}

type DeleteNodeInput struct {
	IP string `json:"ip"`
}

type ImageEntry struct {
	// 存储目录名（与 list 输出第一列一致，用于 rm 指定）
	Name string `json:"name"`
	// 镜像引用名（来自 OCI annotation 或 name）
	Ref string `json:"ref"`
	// 镜像在本地存储的完整路径
	Path string `json:"path"`
}

type Label struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type LabelInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type Node struct {
	IP       string   `json:"ip"`
	Port     *string  `json:"port,omitempty"`
	Username string   `json:"username"`
	Password string   `json:"password"`
	Labels   []*Label `json:"labels"`
}

type NodeList struct {
	Nodes []*Node `json:"nodes"`
}

type Pipeline struct {
	Name string `json:"name"`
	Dag  string `json:"dag"`
}

type PipelineRunTask struct {
	TaskID string `json:"taskId"`
	Data   string `json:"data"`
}

type Query struct {
}

type RunPipelineInput struct {
	PipelineName string                  `json:"pipelineName"`
	Nodes        []*RunPipelineNodeInput `json:"nodes"`
}

type RunPipelineNodeInput struct {
	IP       string        `json:"ip"`
	Port     *string       `json:"port,omitempty"`
	Username string        `json:"username"`
	Password string        `json:"password"`
	Labels   []*LabelInput `json:"labels"`
}

type ServerInfo struct {
	Version         string `json:"version"`
	Commit          string `json:"commit"`
	Date            string `json:"date"`
	BuiltBy         string `json:"builtBy"`
	CurrentDateTime string `json:"currentDateTime"`
}

type UpdateNodeInput struct {
	IP       string        `json:"ip"`
	Port     *string       `json:"port,omitempty"`
	Username string        `json:"username"`
	Password string        `json:"password"`
	Labels   []*LabelInput `json:"labels"`
}
