package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/tangxusc/ar/backend/pkg/command"
	"github.com/tangxusc/ar/backend/pkg/graph/model"
)

// ServerInfo is the resolver for the serverInfo field.
func (r *queryResolver) ServerInfo(ctx context.Context) (*model.ServerInfo, error) {
	return &model.ServerInfo{
		Version: command.Version,
		Commit:  command.Commit,
		Date:    command.Date,
		BuiltBy: command.BuiltBy,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
