package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/tangxusc/ar/backend/pkg/config"
	"github.com/tangxusc/ar/backend/pkg/graph/model"
	"github.com/tangxusc/ar/backend/pkg/pipeline"
)

// ImageDelete is the resolver for the imageDelete field.
func (r *mutationResolver) ImageDelete(ctx context.Context, name string) (bool, error) {
	if err := pipeline.DeleteImage(config.ImagesStoreDir, name); err != nil {
		return false, err
	}
	return true, nil
}

// ImagePrune is the resolver for the imagePrune field.
func (r *mutationResolver) ImagePrune(ctx context.Context, all *bool) ([]string, error) {
	if all != nil && *all {
		return pipeline.PruneAllImages(config.ImagesStoreDir)
	}
	return pipeline.PruneImages(config.ImagesStoreDir, config.PipelinesDir)
}

// Images is the resolver for the images field.
func (r *queryResolver) Images(ctx context.Context) ([]*model.ImageEntry, error) {
	return listImages()
}
