package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/tangxusc/ar/backend/pkg/graph/model"
)

// Pipelines is the resolver for the pipelines field.
func (r *queryResolver) Pipelines(ctx context.Context) ([]*model.Pipeline, error) {
	panic(fmt.Errorf("not implemented: Pipelines - pipelines"))
}

// Pipeline is the resolver for the pipeline field.
func (r *queryResolver) Pipeline(ctx context.Context, name string) (*model.Pipeline, error) {
	panic(fmt.Errorf("not implemented: Pipeline - pipeline"))
}
